import Head from 'next/head';
import Link from "next/link";
import styles from '../../styles/Home.module.css';
import { client, requestBuilder, headers } from "/lib/client";

function ReviewsToApprove(data) {
  const reviews = data.results.results;
  return (
    <div className={styles.container}>
      <Head>
        <title>To Approve Reviews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.grid}> To Approve Reviews </h1>
        <button className="px-4 h-8 uppercase font-semibold tracking-wider border-2 border-black bg-teal-400 text-black">
          <Link href={`/admin/reviews`}>All Reviews</Link>
        </button>
        {reviews.map(review => 
          <div key={review.id} className={styles.card}>
            <div>Title: {review.title}</div>
            <div>Name: {review.authorName}</div>
            <div className={styles.description}>Review: {review.text}</div>
            <div>Rating: {review.rating}</div>
            <button
                className="px-6 h-12 uppercase font-semibold tracking-wider border-2 border-black bg-teal-400 text-black"
                onClick={approveReview}
              >
                Approve
              </button>
          </div>
        )}
      </main>
    </div>
  )
};

const approveReview = () => {
  console.log("hello");
};

export async function getServerSideProps() {
  const to_approve_id = "7ae261ee-ce3b-416c-bd0c-4b457acfc9fa"
  const results = await client
  .execute({
    uri: requestBuilder.reviews
      .where(
        `state(id = "${to_approve_id}")`
      )
      .build(),
    method: "GET",
    headers,
  })
  .then((result) => {
    return result.body;
  })
  .catch((error) => {
    console.log({ error });
  });
  return {
    props: {results}
  }
}

export default ReviewsToApprove