import Head from 'next/head'
import styles from '../../styles/Home.module.css'

function Review(data) {
  const reviews = data.results;
  return (
    <div className={styles.container}>
      <Head>
        <title>Reviews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.grid}> Reviews </h1>
        {reviews.map(review => 
          <div key={review.id} className={styles.card}>
            <div>Title: {review.title}</div>
            <div>Name: {review.authorName}</div>
            <div className={styles.description}>Review: {review.text}</div>
            <div>Rating: {review.rating}</div>
          </div>
        )}
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const reviewsUrl = `${process.env.CTP_API_URL}/${process.env.CTP_PROJECT_KEY}/reviews`;
  const res = await fetch(reviewsUrl, {
    method: 'get',
    headers: {
      'Authorization': `Bearer ${process.env.CTP_ACCESS_TOKEN}`
    }
  })
  const data = await res.json();
  const results = data.results;

  return {
    props: {results}
  }
}

export default Review