import Head from 'next/head';
import Link from "next/link";
import styles from '../../styles/Home.module.css';
import { headers } from "/lib/client";

function Review(data) {
  const reviews = data.results;
  return (
    <div className={styles.container}>
      <Head>
        <title>All Reviews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1> All Reviews </h1>
        <button className="px-4 h-8 uppercase font-semibold tracking-wider border-2 border-black bg-teal-400 text-black">
          <Link href={`/admin/reviews_to_approve`}>Reviews To Approve</Link>
        </button>
        <div className={styles.grid}>
          {reviews.map(review => 
            <div key={review.id} className={styles.card}>
              <div>Title: {review.title}</div>
              <div>Name: {review.authorName}</div>
              <div className={styles.description}>Review: {review.text}</div>
              <div>Rating: {review.rating}</div>
            </div>
          )}
        </div>
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const reviewsUrl = `${process.env.NEXT_PUBLIC_CT_URL}reviews`;
  const res = await fetch(reviewsUrl, {
    method: 'get',
    headers
  })
  const data = await res.json();
  const results = data.results;

  return {
    props: {results}
  }
}

export default Review