import { useState, useEffect } from "react";

import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";

export default function ProductDetails(props) {
  const [formData, setFormData] = useState({
    authorName: "",
    title: "",
    text: "",
    rating: "",
    target: {
      typeId: "product",
      id: props.product_id,
    },
    // state: {
    //   key: "to-approve",
    // },
  });

  const submitForm = (event) => {
    event.preventDefault();

    const formDataParsed = formData;
    formDataParsed.rating = Number(formDataParsed.rating);
    fetch(
      `${process.env.NEXT_PUBLIC_CTP_API_URL}/${process.env.NEXT_PUBLIC_CTP_PROJECT_KEY}/reviews`,
      {
        method: "post",
        headers: {
          Authorization: `Bearer ${process.env.NEXT_PUBLIC_CT_ACCESS_TOKEN}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify(formDataParsed),
      }
    )
      .then((res) => res.json())
      .then((results) => {
        console.log(results);
      })
      .catch((err) => console.log(err));
  };

  const handleInputChange = (event) => {
    setFormData({ ...formData, [event.target.name]: event.target.value });
  };

  console.log({ formData });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{`Review for ${props.product_id}`}</h1>
        <form onSubmit={submitForm}>
        <label>
            Author Name:
            <input
              name="authorName"
              value={formData.authorName}
              onChange={handleInputChange}
            />
          </label>
          <br />
          <label>
            title:
            <input
              name="title"
              value={formData.title}
              onChange={handleInputChange}
            />
          </label>
          <br />
          <label>
            text:
            <input
              name="text"
              value={formData.text}
              onChange={handleInputChange}
            />
          </label>
          <br />
          <label>
            rating:
            <input
              name="rating"
              type="number"
              value={formData.rating}
              onChange={handleInputChange}
            />
          </label>
          <br />
          <input type="submit" value="Submit"></input>
        </form>
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  console.log({ context });
  return {
    props: { product_id: context.params.product_id }, // will be passed to the page component as props
  };
}
